export const tableHeader = {
  urlListHeaders: [
    "NAME",
    "URL",
    "UPLOADED BY",
    "SCRAPING OPTION",
    "LAST TRAINED",
    "ACTIONS",
  ],
  filesListHeaders: ["DATE", "NAME", "TYPE", "UPLOADED BY", "ACTIONS"],
  driveFilesListHeaders: ["DATE", "DRIVE URL", "UPLOADED BY", "ACTIONS"],
  apiKeyListHeaders: ["NAME", "KEY", "CREATED AT", "ACTIONS"],
  feedbackListHeaders: [
    "DATE",
    "SENDER",
    "QUERY",
    "RESPONSE",
    "FEEDBACK",
    "STATUS",
    "ACTIONS",
  ],
  faqListHeaders: ["QUESTION", "CREATED AT", "UPDATED AT", "ACTIONS"],
  chatListHeaders: ["DATE", "CHAT TITLE", "MESSAGES", "STATUS", "ACTIONS"],
  messageListHeaders: ["MESSAGE", "FEEDBACK", "STATUS"],
};
